### ISSUE TITLE
Past Presenters

### ISSUE THREAD

**Issue by notshi** [caprenter/bcb-website#105]
Look at current presenter pages and mark non-active as past presenters.

Past presenters could live on their own page / section.

**Comment by caprenter** [comment]
In wordpress I could select presenters from a list and mass edit them. 

I've put them into draft, which means they still exist but are unplublished.

I also tagged them as past presenter and maybe as past presenters - so that needs bearing in mind!

I think we can live without displaying them for now

**Comment by notshi** [comment]
This seems sufficient for now, thank you!
