### ISSUE TITLE
Music Blog

### ISSUE THREAD

**Issue by notshi** [caprenter/bcb-website#124]
The music blog hasn't been updated since 15 June 2019 - should the link have a prominent space on the website as it does now (header link)?

We could put the link in the footer / under projects / or not at all, etc. It seems like a link to promote a radioshow which is a little strange but in the about page, it seems to have been a hub for BCB music presenters at one point tho clearly, that's no longer the case.

**Comment by caprenter** [comment]
Part of the reason is that the server was updated in June 2019 and then the blog broke becuase of php versions.

It's recently been updated to a modern wordpress and works now. 

We had a recent discussion about 'now it's working...' will presenters use it again - but we haven't had that conversation with presenters yet. JE said it did provide a place to put a lot of information that you can't put in your podcasting platform

**Comment by notshi** [comment]
Ahh, ok - guess we just leave it there at the same place then?

**Comment by notshi** [comment]
Oh, looks like this was raised here a long time ago - https://github.com/caprenter/bcb-website/issues/2

**Comment by notshi** [comment]
Happy to move it to the footer for now actually until it sorts itself out.

**Comment by caprenter** [comment]
I've moved it to the footer to get the programmes pages in.  I'll add the music blog to the tasks for the staff to deal with in terms of getting it used.
