### ISSUE TITLE
This week on BCB box

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#53]
Would be nice to have a template to put 'this week on BCB' box on the front page

**Comment by notshi** [comment]
I've made a draft page - "A Template" which you can edit the content and then copy/paste to the main front page. It should look like this (using placeholder content).

![week_bcb](https://user-images.githubusercontent.com/1515961/42523662-46fe12ba-8466-11e8-85f1-f38a8b62070b.png)

![week_bcb_mob](https://user-images.githubusercontent.com/1515961/42524230-d17c8704-8467-11e8-8f24-1f529066b751.png)

As long as we keep the same format, all should work out ok. Mobile versions should also be ok but will need more checking.

**Do remember to add new content to the mobile-home as well**, otherwise it won't be seen by users visiting the website on their phones.

**Comment by notshi** [comment]
- Fixed headline centering for desktop and mobile.
- Fixed Roboto fonts @import, included both 400 (regular) and 700 (bold) weight so bold renders properly on platforms.

**Comment by notshi** [comment]
- Fixed h2 title size for mobile.
